#
# Qingcloud Dockerfile
#

# Pull base image.
FROM docker.io/lkalbert001/rseqc:latest

# Define mountable directories.
MAINTAINER hexing "hexing@yunify.com"

# Define working directory.
WORKDIR /work
ADD ./sh/gene-analyse ./
ADD ./sh/build.json ./
ADD ./sh/gtf2bed12.perl ./
ADD ./sh/bamdst ./
ADD ./sh/stringtie ./
ADD ./sh/gffcompare ./
ENV PATH /work:$PATH
# Define default command.
CMD ["/work/gene-analyse","report"]
