FROM docker.io/conda/miniconda3

# Define mountable directories.
MAINTAINER hexing "hexing@yunify.com"
#
# # Define working directory.
# WORKDIR /work
#
# ADD ./soft/subread-1.6.0-Linux-x86_64.tar.gz /usr/local/featurecounts
# #ADD ./soft/jdk-15.0.1_linux-x64_bin.tar.gz  /usr/local/java
# #ADD ./soft/fastqc.tar.gz /usr/local/fastqc
# #ADD ./sh/gene-analyse /work
# #RUN tar zxcf /mnt/tar zxcf subread-1.6.0-Linux-x86_64.tar.gz
RUN conda update -n base -c defaults conda && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main && conda config --set show_channel_urls yes  && conda config --add channels bioconda &&  conda install -y fastp  samtools htslib gatk \
&& conda install -c bioconda bwa
# #multiqc gffread
#
#
# # Define default command.
CMD ["echo","build"]
#
